import { configureHardware } from "@devicescript/servers"

export * from "./driver"
export * from "./core"
export * from "./shtc3"
export * from "./sht30"
export * from "./aht20"
export * from "./ltr390"
export * from "./bme680"
export * from "./ssd1306"
export * from "./characterscreendisplay"
export * from "./indexedscreen"
export * from "./dotmatrix"
export * from "./stlikedisplay"
export * from "./st7735"
export * from "./ST7789"
export * from "./ili9341"
export * from "./uc8151"
export * from "./trafficlight"
export * from "./ledserver"
export * from "./accelerometer"
export * from "./sh110x"
export * from "./da213b"
export * from "./grovergblcd"

export * from "./esp32c3fh4rgb"
export * from "./picobricks"
export * from "./xiaoexpansionboard"
export * from "./xiaogroveshield"
export * from "./wavesharepicolcd114"
export * from "./pimoronipicobadger"
export * from "./kittenbotgrapebit"

configureHardware({ scanI2C: false })
